### ISSUE TITLE
PDS Standards Change: Line Delimiters

### ISSUE THREAD

**Issue by acraugh** [Small-Bodies-Node/pds4_tools#51] opened 2021-08-31 16:37 UTC
PDS4 Standards have changed to allow text delimiters other that CR/LF, effective with the current IM release.  We are starting to get reports from users that pds4_viewer is failing when LF delimiters are specified.

**Comment by jordanpadams** [comment] 2021-09-01 17:24
@acraugh do you have some sample products showing the failure? also the version of pds4_viewer they are using? this upgrade was completed per @LevN0's work here: https://github.com/Small-Bodies-Node/pds4_tools/pull/35

**Comment by acraugh** [comment] 2021-09-01 17:50
Sorry - forgot to include the example Ed G. sent me. Attached as a ZIP.
[collection_eop.zip](https://github.com/Small-Bodies-Node/pds4_tools/files/7093309/collection_eop.zip)

**Comment by LevN0** [comment] 2021-09-01 22:11
It is very likely that #35 fixed the issue, but I have not released a new build of the PDS4 Viewer since that change. I am on vacation this week, will try to look into this when I return as time allows.

**Comment by LevN0** [comment] 2021-09-06 21:26
I have confirmed that the current development version (i.e. current master) works fine with this label. However, a new release/build of the tool is needed, the prior release (v1.2) came before the standards change.

**Comment by jordanpadams** [comment] 2021-09-21 12:54
@LevN0 we have a new release of the PDS4 IM coming up December 1. can we look to get a new tagged release of PDS4 Viewer by then?

**Comment by jordanpadams** [comment] 2021-09-22 14:04
thanks @LevN0 . we are happy to help out here too, just point us to the procedure and/or access to pypi and we can give it is a shot if you don't have the time.

**Comment by LevN0** [comment] 2021-10-12 05:03
Nominally v1.3 has been released, however I expect it will be a few days until it is uploaded to the SBN website.

**Comment by jordanpadams** [comment] 2021-10-12 16:47
thanks @LevN0

**Comment by LevN0** [comment] 2021-10-30 06:31
PDS4 Viewer binaries were released on the SBN website a couple of weeks ago, and include this fix. Marking as resolved.

**Closed by LevN0** 2021-10-30 06:31 UTC
